-- Run this in Supabase SQL editor to create the leads table.
-- Dashboard → SQL Editor → New query → paste → Run.

create table if not exists public.leads (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  name        text not null,
  phone       text not null,
  email       text not null,
  message     text,
  service     text not null,
  page_url    text,
  ip_address  text,
  handled     boolean not null default false,
  notes       text
);

-- Row Level Security: lock the table so only the service_role key (used by the API route)
-- can insert. The anon key cannot read or write.
alter table public.leads enable row level security;

-- Helpful indexes
create index if not exists leads_created_at_idx on public.leads (created_at desc);
create index if not exists leads_service_idx    on public.leads (service);
create index if not exists leads_handled_idx    on public.leads (handled);
